"""TLS context construction for the broker link."""

from __future__ import annotations

import datetime
import ssl
from pathlib import Path
from unittest.mock import patch

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

from whiskerless.mqtt import MqttSettings, build_tls_context, create_client

# Generated exactly as docs/setup/certificates.md instructs, i.e. with no
# keyUsage extension — the shape that VERIFY_X509_STRICT rejects.
_CA_PEM = """\
-----BEGIN CERTIFICATE-----
MIIBkTCCATegAwIBAgIUbv5cT6AeImdHK4tWs4H5EQt8mfIwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTd2hpc2tlcmxlc3MgdGVzdCBDQTAeFw0yNjA4MDgyMDA3NDZa
Fw0zNjA4MDUyMDA3NDZaMB4xHDAaBgNVBAMME3doaXNrZXJsZXNzIHRlc3QgQ0Ew
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT+bAU4rqmcUBhh1McWW8PCWnbtrZ7U
nzOw4U3KYYj/9+z4mVj511P6t8IM5DTpvZFxM2816caUz7RNjLaZ3wkOo1MwUTAd
BgNVHQ4EFgQUFgX+gfMguo5dojsDsIDz/HYgAhcwHwYDVR0jBBgwFoAUFgX+gfMg
uo5dojsDsIDz/HYgAhcwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBF
AiAA9ts5JpcFJu+ebVYjFPhFr0aCZ+/lXN+3kDs1g203rQIhAJBdSGnvkIT1c5qe
SJx356TxYyvirJIjgfdV9b/ZcUvO
-----END CERTIFICATE-----
"""


def _settings(**kw: object) -> MqttSettings:
    return MqttSettings(host="192.0.2.10", port=8883, tls=True, **kw)  # type: ignore[arg-type]


def test_plaintext_link_has_no_context() -> None:
    assert build_tls_context(MqttSettings(host="192.0.2.10", port=1883, tls=False)) is None


def test_pinned_ca_relaxes_strict_verification_and_nothing_else(tmp_path: Path) -> None:
    # A CA generated by the project's own documented openssl recipe has no
    # keyUsage extension, and 3.13+ rejects that under VERIFY_X509_STRICT. The
    # CA is burned into the robot at provisioning, so refusing is unrecoverable.
    ca = tmp_path / "ca.crt"
    ca.write_text(_CA_PEM)
    context = build_tls_context(_settings(ca_cert_path=str(ca)))
    assert context is not None
    assert not context.verify_flags & ssl.VERIFY_X509_STRICT
    # Everything else that actually protects the connection stays on.
    assert context.verify_mode is ssl.CERT_REQUIRED
    assert context.check_hostname is True
    # And the relaxation must not reach the system roots: pinning a CA means
    # trusting that CA alone, so it is the only cert in the store.
    assert len(context.get_ca_certs()) == 1


def test_system_trust_store_keeps_the_stdlib_defaults() -> None:
    # The relaxation exists for a CA we know the robot was provisioned against.
    # Without one we are trusting the system store, so we must not weaken
    # anything. Compared against the stdlib default rather than asserting a
    # specific flag, because VERIFY_X509_STRICT only became a default in 3.13.
    context = build_tls_context(_settings())
    assert context is not None
    assert context.verify_flags == ssl.create_default_context().verify_flags


def test_inline_ca_data_wins_over_a_path(tmp_path: Path) -> None:
    # Long-standing precedence: a caller passing both gets the in-memory CA, and
    # a stale path must not be able to break an otherwise valid one.
    context = build_tls_context(
        _settings(ca_cert_data=_CA_PEM, ca_cert_path=str(tmp_path / "does-not-exist.crt"))
    )
    assert context is not None
    assert len(context.get_ca_certs()) == 1


def test_hostname_check_is_opt_out_only() -> None:
    context = build_tls_context(_settings(verify_hostname=False))
    assert context is not None
    assert context.check_hostname is False
    # Opting out of hostname matching must not weaken chain verification.
    assert context.verify_mode is ssl.CERT_REQUIRED


async def test_a_client_is_built_from_the_settings_without_connecting() -> None:
    """Construction must not touch the network; a link builds one before connecting.

    Async because aiomqtt binds to the running loop at construction, which is
    itself the reason create_client is separate from connecting.
    """
    client = create_client(MqttSettings(host="192.0.2.10", port=8883, client_id="mine"))
    assert client is not None


def _self_signed(common_name: str = "whiskerless-test") -> tuple[str, str]:
    """A throwaway cert/key pair, built with the library we already depend on.

    Deliberately not `openssl`: the whole reason `cryptography` is a dependency
    is that stock Windows has no openssl binary, so a test that shells out to one
    would fail on the platform the dependency exists to support.
    """
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)])
    now = datetime.datetime.now(datetime.UTC)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(minutes=5))
        .not_valid_after(now + datetime.timedelta(days=1))
        .sign(key, hashes.SHA256())
    )
    return (
        cert.public_bytes(serialization.Encoding.PEM).decode(),
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        ).decode(),
    )


def test_a_client_certificate_is_loaded_into_the_tls_context() -> None:
    """The broker this project now recommends runs `require_certificate true`, so
    the CLI has to identify itself the same way the robot does."""
    cert, key = _self_signed()
    settings = MqttSettings(
        host="broker", ca_cert_data=cert, client_cert_data=cert, client_key_data=key
    )
    with patch("ssl.SSLContext.load_cert_chain", autospec=True) as loaded:
        assert build_tls_context(settings) is not None
    assert loaded.call_count == 1, "the client chain is presented to the broker"


def test_no_client_certificate_means_no_chain_is_loaded() -> None:
    cert, _key = _self_signed()
    settings = MqttSettings(host="broker", ca_cert_data=cert)
    with patch("ssl.SSLContext.load_cert_chain", autospec=True) as loaded:
        assert build_tls_context(settings) is not None
    assert loaded.call_count == 0


def test_a_pem_without_a_trailing_newline_still_parses() -> None:
    """A PEM that came through .strip() would otherwise concatenate into
    "-----END CERTIFICATE----------BEGIN", which is valid on neither side."""
    cert, key = _self_signed()
    settings = MqttSettings(
        host="broker",
        ca_cert_data=cert,
        client_cert_data=cert.strip(),
        client_key_data=key,
    )
    written: list[str] = []
    real = Path.write_text

    def _capture(self: Path, data: str, *a: object, **k: object) -> int:
        written.append(data)
        return real(self, data, *a, **k)

    with patch.object(Path, "write_text", _capture):
        assert build_tls_context(settings) is not None
    assert written, "the pair was materialized"
    assert "-----END CERTIFICATE-----\n-----BEGIN" in written[0]
